### ISSUE TITLE
Gnome 3.20 support

### ISSUE THREAD

**Issue by yggi** [timbertson/shellshape#171]
https://extensions.gnome.org/local/ states "OUTDATED" for shellshape. It does not load. No menu, no tiling.

**Comment by timbertson** [comment]
I've added 3.20 to the metadata on the latest `master` branch, if anyone could test on 3.20 and report back (I don't run it yet), that'd be great. I've already uploaded this to gnome.org as well, but it might take some time for the new version to appear as it needs review.

**Comment by yggi** [comment]
I would like to test in 3.20. I tried to build the latest `master` according to the README, but it ran into an error:

```
iggy@bucky ~/build/shellshape (master) $ ./tools/gup compile
gup  compile
gup    schemas/all
gup      schemas/inputs
gup    shellshape/all
gup      build/gjs/extension.js
gup        build/gjs/.sources
../src/gjs/extension.ts(326,5): error TS7027: Unreachable code detected.
gup      Target `build/gjs/extension.js` failed with exit status 2
gup    Target `shellshape/all` failed with exit status 2
gup  Target `compile` failed with exit status 2
```

The same happend when I tried to build/install from AUR.

**Comment by timbertson** [comment]
Oops, thanks for the heads up. I've removed the dead code (I wasn't seeing this error because I was using an earlier version of typescript). Can you try again please?

**Comment by yggi** [comment]
I tried again (with commit 40782f3), the build runs without errors now and shellshape works again with no obvious problems on gnome-shell 3.20.1 on arch linux.

I have no idea about the internals of these extensions, but would it be possible/reasonable to set the "shell-version" in metadata.json to something like "> 3.12"? So it would be more optimistic to run on future upgrades.

Thank you for your work, shellshape turns gnome from bearbale to usable!

**Comment by timbertson** [comment]
Great, thanks for testing!

But nope, sadly gnome doesn't allow future specifications. In theory this forces people to test against new versions before claiming support it. But in practice it means anyone who upgrades to a new shell version before the author gets their extensions disabled (even if they would work fine). So usually I have to claim support before I can test it anyway (otherwise you'd get stuck without shellshape until I upgrade to the next Fedora release, and you don't want to have to wait for that).
