### ISSUE TITLE
Option to change the highlight colour

### ISSUE THREAD

**Issue by HoratiuMl** [timbertson/shellshape#185]
Hello.

It would be nice if we could change the highlight colour. The current one fits Ubuntu perfectly, but for other distros (Arch in my case) it does not.

It would be nice if the settings menu would have an option to pick a custom RGB colour.
It would be even better if there would also be an option to let the extension automatically pick a colour based on the current GTK theme (the same colour as the mouse drag selection colour).

Is this something that you think you can add as a feature?

Thanks.

**Comment by timbertson** [comment]
What highlight colour do you mean? The only one I can think of is in the top bar, which ought to be pretty consistent across distros. Can you post a screenshot?

**Comment by HoratiuMl** [comment]
When I try to tile a window to one part of the screen, any part, there is a transparent square that highlights the area where the window will be put. The colour of that square is orange, like the highlight colour of Ubuntu, but mine is blue, since I am on Arch.

I would do a screenshot but apparently you can't do screenshots while doing that, for some reason (dunno if it's default GNOME behaviour or is caused by this extension)

**Comment by rhofour** [comment]
I believe that's a standard feature of gnome. Try disabling Shellshape and
see if it still occurs.


On Jan 24, 2017 05:59, "Horațiu Mlendea" <notifications@github.com> wrote:

When I try to tile a window to one part of the screen, any part, there is a
transparent square that highlights the area where the window will be put.
The colour of that square is orange, like the highlight colour of Ubuntu,
but mine is blue, since I am on Arch.

I would do a screenshot but apparently you can't do screenshots while doing
that, for some reason (dunno if it's default GNOME behaviour or is caused
by this extension)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/timbertson/shellshape/issues/185#issuecomment-274772360>,
or mute the thread

**Comment by timbertson** [comment]
Ahh right, yes that's a gnome thing, nothing to do with shellshape (and it doesn't play very well alongside shellshape, unfortunately - I just avoid it, I don't know if it can be turned off)

**Comment by HoratiuMl** [comment]
In default GNOME it's blue. And if I change my theme to a green one, then it's green, and so on.
